// React project/src/components/ExpenseReports.tsx
import React, { useState, useMemo } from 'react';
import { useExpense } from '../store/ExpenseContext';
import { ExpenseReport, ExpenseStatus, mockUsers, mockPolicies, mockExpenseTypes } from '../types/expense';

const ExpenseReports: React.FC = () => {
    const { expenses, currentUser } = useExpense();
    const [statusFilter, setStatusFilter] = useState<ExpenseStatus | 'ALL'>('ALL');
    const [dateFilter, setDateFilter] = useState('');

    const filteredExpenses = useMemo(() => {
        // First filter by user role
        let roleFilteredExpenses = expenses;
        if (currentUser) {
            if (currentUser.role === 'EMPLOYEE') {
                // Employees can only see their own expenses
                roleFilteredExpenses = expenses.filter(expense => expense.employeeId === currentUser.id);
            } else if (currentUser.role === 'MANAGER') {
                // Managers can see their own expenses and their team's expenses
                // In a real app, you would have a proper team structure
                // For now, we'll just show all expenses as a manager
                roleFilteredExpenses = expenses;
            }
            // Admins can see all expenses by default
        }

        // Then apply status and date filters
        return roleFilteredExpenses.filter(expense => {
            const matchesStatus = statusFilter === 'ALL' || expense.status === statusFilter;
            const matchesDate = !dateFilter || expense.date === dateFilter;
            return matchesStatus && matchesDate;
        });
    }, [expenses, statusFilter, dateFilter, currentUser]);

    const getEmployeeName = (employeeId: string) => {
        return mockUsers.find(user => user.id === employeeId)?.name || 'Unknown Employee';
    };

    const getPolicyName = (policyId: string) => {
        return mockPolicies.find(policy => policy.id === policyId)?.name || 'Unknown Policy';
    };

    const getExpenseTypeName = (expenseTypeId: string) => {
        return mockExpenseTypes.find(type => type.id === expenseTypeId)?.name || 'Unknown Type';
    };

    // Function to calculate total amount for a report
    const getTotalAmount = (expense: ExpenseReport) => {
        return expense.expenses.reduce((sum, item) => sum + item.amount, 0);
    };

    const statistics = useMemo(() => {
        const stats = {
            totalAmount: 0,
            byPolicy: {} as Record<string, number>,
            byStatus: {} as Record<string, number>,
            byEmployee: {} as Record<string, number>,
            byExpenseType: {} as Record<string, number>
        };

        filteredExpenses.forEach(expense => {
            const totalAmount = getTotalAmount(expense);
            stats.totalAmount += totalAmount;
            
            // By policy
            const policyName = getPolicyName(expense.policyId);
            stats.byPolicy[policyName] = (stats.byPolicy[policyName] || 0) + totalAmount;
            
            // By status
            stats.byStatus[expense.status] = (stats.byStatus[expense.status] || 0) + totalAmount;
            
            // By employee
            stats.byEmployee[expense.employeeId] = (stats.byEmployee[expense.employeeId] || 0) + totalAmount;

            // By expense type - now we need to handle multiple expense types per report
            expense.expenses.forEach(item => {
                const expenseTypeName = getExpenseTypeName(item.expenseTypeId);
                stats.byExpenseType[expenseTypeName] = (stats.byExpenseType[expenseTypeName] || 0) + item.amount;
            });
        });

        return stats;
    }, [filteredExpenses]);

    return (
        <div className="space-y-6">
            {/* Filters */}
            <div className="bg-white shadow rounded-lg p-6">
                <h3 className="text-lg font-medium mb-4">Filters</h3>
                <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                    <div>
                        <label className="block text-sm font-medium text-gray-700">
                            Status
                        </label>
                        <select
                            value={statusFilter}
                            onChange={(e) => setStatusFilter(e.target.value as ExpenseStatus | 'ALL')}
                            className="mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-indigo-500 focus:ring-indigo-500 sm:text-sm"
                        >
                            <option value="ALL">All Statuses</option>
                            <option value="PENDING">Pending</option>
                            <option value="APPROVED">Approved</option>
                            <option value="REJECTED">Rejected</option>
                            <option value="REIMBURSED">Reimbursed</option>
                        </select>
                    </div>
                    <div>
                        <label className="block text-sm font-medium text-gray-700">
                            Date
                        </label>
                        <input
                            type="date"
                            value={dateFilter}
                            onChange={(e) => setDateFilter(e.target.value)}
                            className="mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-indigo-500 focus:ring-indigo-500 sm:text-sm"
                        />
                    </div>
                </div>
            </div>

            {/* Expense List */}
            <div className="bg-white shadow rounded-lg p-6">
                <h3 className="text-lg font-medium mb-4">Expense List</h3>
                <div className="overflow-x-auto">
                    <table className="min-w-full divide-y divide-gray-200">
                        <thead className="bg-gray-50">
                            <tr>
                                <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                                    Employee
                                </th>
                                <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                                    Date
                                </th>
                                <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                                    Expense Types
                                </th>
                                <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                                    Total Amount
                                </th>
                                <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                                    Status
                                </th>
                            </tr>
                        </thead>
                        <tbody className="bg-white divide-y divide-gray-200">
                            {filteredExpenses.map((expense: ExpenseReport) => (
                                <tr key={expense.id}>
                                    <td className="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-900">
                                        {getEmployeeName(expense.employeeId)}
                                    </td>
                                    <td className="px-6 py-4 whitespace-nowrap text-sm text-gray-500">
                                        {new Date(expense.date).toLocaleDateString()}
                                    </td>
                                    <td className="px-6 py-4 text-sm text-gray-500">
                                        <div className="space-y-1">
                                            {expense.expenses.map((item, index) => (
                                                <div key={index}>
                                                    <span className="font-medium">{getExpenseTypeName(item.expenseTypeId)}</span>
                                                    <span className="text-gray-400 ml-2">₹{item.amount.toFixed(2)}</span>
                                                </div>
                                            ))}
                                        </div>
                                    </td>
                                    <td className="px-6 py-4 whitespace-nowrap text-sm text-gray-500">
                                        ₹{getTotalAmount(expense).toFixed(2)}
                                    </td>
                                    <td className="px-6 py-4 whitespace-nowrap">
                                        <span className={`px-2 inline-flex text-xs leading-5 font-semibold rounded-full
                                            ${expense.status === 'APPROVED' ? 'bg-green-100 text-green-800' : ''}
                                            ${expense.status === 'PENDING' ? 'bg-yellow-100 text-yellow-800' : ''}
                                            ${expense.status === 'REJECTED' ? 'bg-red-100 text-red-800' : ''}
                                            ${expense.status === 'REIMBURSED' ? 'bg-blue-100 text-blue-800' : ''}
                                        `}>
                                            {expense.status}
                                        </span>
                                    </td>
                                </tr>
                            ))}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    );
};

export default ExpenseReports;

// src/app/pages/expense-reports/expense-reports.component.ts
import { Component, OnInit } from '@angular/core';
import { ExpensePolicy, ExpenseReport, ExpenseStatus, mockPolicies, mockExpenses } from '../../types/expense';
import { ExpenseService } from '../../services/expense.service';

// Mock expense reports data
const mockReports: ExpenseReport[] = [
  {
    id: '1',
    date: '2024-05-15',
    totalAmount: 250.00,
    status: 'APPROVED',
    employeeId: '1',
    policyId: '1',
    items: [
      {
        id: '1',
        expenseType: '1',
        amount: 100.00,
        description: 'Business lunch with client',
        receiptFile: 'lunch_receipt.pdf',
        date: '2024-05-15'
      },
      {
        id: '2',
        expenseType: '2',
        amount: 150.00,
        description: 'Taxi fare to client meeting',
        receiptFile: 'taxi_receipt.pdf',
        date: '2024-05-15'
      }
    ]
  },
  {
    id: '2',
    date: '2024-05-10',
    totalAmount: 120.00,
    status: 'PENDING',
    employeeId: '1',
    policyId: '1',
    items: [
      {
        id: '3',
        expenseType: '3',
        amount: 120.00,
        description: 'Office supplies',
        receiptFile: 'office_supplies_receipt.pdf',
        date: '2024-05-10'
      }
    ]
  },
  {
    id: '3',
    date: '2024-05-05',
    totalAmount: 350.00,
    status: 'REJECTED',
    employeeId: '1',
    policyId: '1',
    items: [
      {
        id: '4',
        expenseType: '4',
        amount: 350.00,
        description: 'Conference registration',
        receiptFile: 'conference_receipt.pdf',
        date: '2024-05-05'
      }
    ]
  }
];

@Component({
  selector: 'app-expense-reports',
  templateUrl: './expense-reports.component.html',
  styleUrls: ['./expense-reports.component.scss']
})
export class ExpenseReportsComponent implements OnInit {
  displayedColumns: string[] = ['date', 'amount', 'status', 'details'];
  submittedReports: ExpenseReport[] = [];
  selectedReport: ExpenseReport | null = null;
  expenseTypes: Record<string, string> = {};

  constructor(private expenseService: ExpenseService) {
    // Get expense types for display
    this.expenseService.getExpenseTypes().subscribe(types => {
      this.expenseTypes = types.reduce((acc, type) => {
        acc[type.id] = type.name;
        return acc;
      }, {} as Record<string, string>);
    });

    // Subscribe to expenses from service
    this.expenseService.expenses$.subscribe(reports => {
      this.submittedReports = reports;
      // Calculate total amount for each report
      this.submittedReports.forEach(report => {
        report.totalAmount = report.items.reduce((total, item) => total + item.amount, 0);
      });
    });
  }

  viewReportDetails(report: ExpenseReport): void {
    this.selectedReport = report;
  }

  closeDetails(): void {
    this.selectedReport = null;
  }

  formatDate(date: string): string {
    return new Date(date).toLocaleDateString();
  }

  ngOnInit() {
    // Sort reports by date (newest first)
    this.submittedReports = [...this.submittedReports].sort((a, b) => 
      new Date(b.date).getTime() - new Date(a.date).getTime()
    );
  }


}
<div class="bg-white shadow rounded-lg p-6">
  <div class="flex justify-between items-center mb-6">
    <h2 class="text-xl font-semibold text-gray-900">Expense Reports</h2>
  </div>

  <div class="overflow-x-auto">
    <table class="min-w-full divide-y divide-gray-200">
      <thead class="bg-gray-50">
        <tr>
          <th class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Date</th>
          <th class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Amount</th>
          <th class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Status</th>
          <th class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Details</th>
        </tr>
      </thead>
      <tbody class="bg-white divide-y divide-gray-200">
        <tr *ngFor="let report of submittedReports">
          <td class="px-6 py-4 whitespace-nowrap">
            {{formatDate(report.date)}}
          </td>
          <td class="px-6 py-4 whitespace-nowrap">
            ${{report.totalAmount.toFixed(2)}}
          </td>
          <td class="px-6 py-4 whitespace-nowrap">
            <span class="inline-flex items-center px-3 py-1 rounded-full text-sm font-medium" 
                  [ngClass]="{
                    'bg-green-100 text-green-800': report.status === 'APPROVED',
                    'bg-yellow-200 text-yellow-800': report.status === 'PENDING',
                    'bg-red-100 text-red-800': report.status === 'REJECTED'
                  }">
              {{report.status}}
            </span>
          </td>
          <td class="px-6 py-4 whitespace-nowrap">
            <button (click)="viewReportDetails(report)"
                    class="inline-flex items-center px-4 py-2 border border-transparent text-sm font-medium rounded-md text-white bg-blue-600 hover:bg-blue-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-blue-500">
              View Details
            </button>
          </td>
        </tr>
      </tbody>
    </table>
  </div>

  <div class="mt-6 text-center" *ngIf="submittedReports.length === 0">
    <p class="text-gray-500">No submitted expense reports found.</p>
  </div>

  <!-- Details Modal -->
  <div *ngIf="selectedReport" class="fixed inset-0 bg-gray-600 bg-opacity-50 overflow-y-auto h-full w-full">
    <div class="relative top-20 mx-auto p-5 border w-96 shadow-lg rounded-md bg-white">
      <div class="flex justify-between items-center pb-3">
        <h3 class="text-2xl font-bold">Expense Details</h3>
        <button (click)="closeDetails()" class="text-black hover:text-gray-500">
          <svg class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12" />
          </svg>
        </button>
      </div>

      <div class="my-2">
        <div class="flex justify-between mb-2">
          <span class="text-gray-600">Date:</span>
          <span>{{formatDate(selectedReport.date)}}</span>
        </div>
        <div class="flex justify-between mb-2">
          <span class="text-gray-600">Total Amount:</span>
          <span>₹{{selectedReport.totalAmount.toFixed(2)}}</span>
        </div>
        <div class="flex justify-between mb-2">
          <span class="text-gray-600">Status:</span>
          <span [ngClass]="{
            'text-green-600': selectedReport.status === 'APPROVED',
            'text-yellow-600': selectedReport.status === 'PENDING',
            'text-red-600': selectedReport.status === 'REJECTED'
          }">
            {{selectedReport.status}}
          </span>
        </div>
      </div>

      <div class="mt-4">
        <h4 class="font-semibold mb-2">Expense Items</h4>
        <div class="space-y-2">
          <div *ngFor="let item of selectedReport.items" class="flex justify-between border-b pb-2">
            <div class="flex-1">
              <div class="font-medium">{{item.description}}</div>
              <div class="text-sm text-gray-600">{{expenseTypes[item.expenseType] || 'Unknown'}}</div>
              <div class="text-sm text-gray-600">₹{{item.amount.toFixed(2)}}</div>
            </div>
            <div class="text-sm text-gray-600">{{formatDate(item.date)}}</div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
